api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    formats:
        jsonhal:  ['application/hal+json']
        json:     ['application/json']
        html:     ['text/html']

    swagger:
       api_keys:
           apiKey:
              name: Authorization
              type: header

    enable_swagger_ui: true

    enable_swagger: true

    collection:
        pagination:
            items_per_page: 5

    title: 'BileMo'

doctrine:
    orm:
        filters:
            user_filter:
                class: App\Filter\UserFilter