api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    formats:
        jsonhal:  ['application/hal+json']
        json:     ['application/json']
        html:     ['text/html']

    swagger:
       api_keys:
           apiKey:
              name: Authorization
              type: header