api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    formats:
        jsonhal:  ['application/hal+json']
        json:     ['application/json']
        html:     ['text/html']

    swagger:
       api_keys:
           apiKey:
              name: Authorization
              type: header

    enable_swagger_ui: true

    enable_swagger: true

    collection:
        pagination:
            items_per_page: 5

    http_cache:
        etag: true
        invalidation:
            enabled: true
            #varnish_urls: ['%env(VARNISH_URL)%']
        max_age: 3600

    exception_to_status:
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400

    title: 'BileMo'

    description: 'Web service exposing a business to business API'

    version: '1.0.0'

doctrine:
    orm:
        filters:
            user_filter:
                class: App\Filter\UserFilter